### ISSUE TITLE
Add Travis

### ISSUE THREAD

**Issue by grinnellm** [grinnellm/SpawnIndex#12]

**Comment by grinnellm** [comment]
Because the MS Access database requires a Microsoft Access Driver, Travis will fail until the option `os: windows` can use **R**. Currently this option gets the error: "The language 'r' is currently unsupported on the Windows Build Environment."

**Comment by grinnellm** [comment]
Contents of ".travis.yml" are now in "travis.txt."

**Comment by grinnellm** [comment]
Switch from Travis to GitHub Actions

**Comment by andrew-edwards** [comment]
Was Actions fairly easy to set up. I switched my Travis from .org to .com (or maybe it was vice versa, whatever they asked for) before Xmas for a bunch of repos, which then all started failing (but build fine locally). I see that Sean has started switching to Actions and briefly looked into it.

**Comment by andrew-edwards** [comment]
Your new .yaml file looks much more complicated than my usual Travis ones - that's what put me off this morning when I started looking around.....

**Comment by grinnellm** [comment]
It does look quite complicated, but I copied it directly from one of Sean's!

**Comment by andrew-edwards** [comment]
Though, it still shows at failing ;)  I see you were trying to wrestle with vignettes (that might be a vignette path thing rather than GitHub Actions).

**Comment by grinnellm** [comment]
Yeah it's still failing in `R CMD check` (was failing here in Travis too). I think you're right -- it may be failing because I pull the data from an MS Access database, and the platform might not have the correct drivers? I'm not really sure. The `check` runs fine locally. I tried omitting the vignette (option `--no-build-vignettes`) but that didn't work either. Probably user/implementation error:)
