### ISSUE TITLE
Vignette fails on `devtools::check()`

### ISSUE THREAD

**Issue by grinnellm** [grinnellm/SpawnIndex#20]
==> devtools::check()

Updating SpawnIndex documentation
Writing NAMESPACE
Loading SpawnIndex
Writing NAMESPACE
-- Building --------------------------------------------------------------------------------- SpawnIndex --
Setting env vars:
* CFLAGS    : -Wall -pedantic -fdiagnostics-color=always
* CXXFLAGS  : -Wall -pedantic -fdiagnostics-color=always
* CXX11FLAGS: -Wall -pedantic -fdiagnostics-color=always
-----------------------------------------------------------------------------------------------------------
v  checking for file 'C:\Grinnell\Git\SpawnIndex/DESCRIPTION' (589ms)
-  preparing 'SpawnIndex': (29.7s)
v  checking DESCRIPTION meta-information ... 
-  installing the package to process help pages (507ms)
   Loading required namespace: SpawnIndex
-  saving partial Rd database (7.7s)
E  creating vignettes (7.9s)
   Error: file 'C:/Users/grinnellm/AppData/Local/Temp/2/RtmpWYfz0V/Rbuild2a7860df6d3f/SpawnIndex/DESCRIPTION' is not in valid DCF format
   In addition: Warning message:
   In read.dcf(dfile, keep.white = .keep_white_description_fields) :
     cannot open compressed file 'C:/Users/grinnellm/AppData/Local/Temp/2/RtmpWYfz0V/Rbuild2a7860df6d3f/SpawnIndex/DESCRIPTION', probable reason 'Permission denied'
   Execution halted
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command error
Calls: <Anonymous> ... with_envvar -> force -> do.call -> <Anonymous> -> throw
Execution halted

Exited with status 1.

**Comment by grinnellm** [comment]
Tried [this](https://community.rstudio.com/t/devtools-check-error-with-vignette-but-vignette-can-be-knitted-without-problem/55962) but it didn't seem to work.

**Comment by grinnellm** [comment]
Seems like any vignette fails, even if I just try the one created by `usethis::use_vignette("my-vignette")`. If I delete the vignettes folder, all works OK.

**Comment by grinnellm** [comment]
Now this doesn't fail (since I omitted the vignette from the check in [this commit](https://github.com/grinnellm/SpawnIndex/commit/55726689c64650edcee77934474a35e85460c680)), but there are two warnings:
> checking files in 'vignettes' ... WARNING
  Files in the 'vignettes' directory but no files in 'inst/doc':
    'Introduction.Rmd'

> checking package vignettes in 'inst/doc' ... WARNING
  dir.exists(dir) is not TRUE
  Package vignette without corresponding single PDF/HTML:
     'Introduction.Rmd'

**Comment by grinnellm** [comment]
Not sure why, but this is working now.

**Comment by andrew-edwards** [comment]
Did you do `build_vignettes()` at some point? Have to be careful as that uses `library(pkgname)` which may not be as up-to-date as your local version in your directory (loaded using `load_all()`. So maybe you updated it in your library and then it worked.

**Comment by grinnellm** [comment]
I may have, but I can't recall. I did update all my packages including R recently, so maybe that was it?
