### ISSUE TITLE
AE comments re subscripts and equations

### ISSUE THREAD

**Issue by grinnellm** [grinnellm/SpawnIndex#32]
- [x] Lines 94-96 are a bit unclear.

- [x] L113 - I originally thought that I agree to simplify the notation by suppressing the subscripts (though this can get you into trouble, as everything isn't explicit), but it took me a while to realise what you meant. Suggest just giving an example, i.e.  Q is really Q_{xnryt} [in whatever order you're using] but subscripts are dropped for simplicity.  And I think you're missing t on line 113?

- [x] However, now I'm looking again - I think rho in (1) also depends on n, r and y (maybe x?) because Q does. So by dropping some of the extra subscripts it can quickly get ambiguous. That multi-subscript example we had in the notation paper is like yours, and looks cumbersome at first but is actually very clear. Presumably you have rho in different years, but this isn't clear.

- [x] Also, if you did have all the subscripts in Table 1, you then wouldn't have to keep repeating the 'type x, spawn s, ....' details in the Description column, could just do for the first one. If you do go with the subscripts, if possible they should always be in the same order each time, but I'm not sure if that's going to be possible (and is probably okay).

- [x] Table 1 - also give the same example in caption, so that Table can be read alone. 

- [x] Table 1 - suggest grouping the indices first, followed by the variables, which I think are  (not sure I could see where p gets used), though (reading the caption again) these are all indices aren't they (I think some of them are being mentioned later, which I didn't get to)....   Actually - I think the issue is that early ones refer to later ones - could re-order by starting with  y and  r, then n (since N_ry) then s (since S_nry) etc. 

- [x] Table 1, x goes from 1, 2, 3, ..., X , but can you have X>3 (thought there were just three types)

- [x] Minor - probably 10^3 eggs m^-2 rather than eggs 10^3 m^-2

- [x] I didn't get past apage 10. I see you have S_xnry on page 10 (you did say only dropping the subscripts in section 2.2.1), and lots of subscripts in (26) [but they're nice and consistent looking], so maybe it is best to keep them throughout. Eqn (4) would get nasty, so maybe use \bar{rho_{ts}} etc. there, defining it in the next line (though may be just as bad; maybe stick with nasty equation).

**Comment by grinnellm** [comment]
Yes @andrew-edwards there are only spawn survey types now (X=3; bullet 7), but there could be more at some point, even for historic data if we update something. Like if we add SOK spawn to the index. Maybe I should I just omit the "3, ..." from the range for x be "1, 2, X"? Note I've updated the table a bit to now include all the subscripts. Maybe it should be the same for R, the number of SARs (there are 7).
![image](https://user-images.githubusercontent.com/25674027/106038564-f4949c00-608c-11eb-9b6f-e5c1f47c5b6b.png)

**Comment by andrew-edwards** [comment]
Yes, maybe omit the 3, but no big deal.
Table looks good - is more complex but more explicit (like the example we gave in the notation manuscript). And show the hierarchical structure of the data.

**Comment by grinnellm** [comment]
Can you check something before I go "full subscript" as it were? Eq (1)
![image](https://user-images.githubusercontent.com/25674027/106035781-57843400-6089-11eb-8398-064726ecd46d.png)
would get updated to (note the double subscripts, as in `\rho_{q_{txsnry}}` and ``\mean{\rho_{t_{xsnry}}}``)
![image](https://user-images.githubusercontent.com/25674027/106038822-41787280-608d-11eb-98cd-72c9b5d057f2.png)
Is that right?

**Comment by andrew-edwards** [comment]
I think the other day I wondered if you needed the double subscript, but was hoping not. You can't just have on the LHS:
```\mean{rho_{txsnry}}```  

 i.e. just leave out the q index, as that's what you've averaged over? 

But then you might get in a mess if you have to do other similar averages (just don't ever replace the index letters which actual numbers!). You could get fancy and do:
```\mean{rho_{\bar{q}txsnry}}```
if that shows up okay. So be explicit that you've averaged over q. Then every `\rho_.....` will have all the indices in.

**Comment by grinnellm** [comment]
To me it seems like the double subscripts might be easiest in a way, simplest for me anyways. Is that a bad approach? That way it also matches Table 1.

**Comment by andrew-edwards** [comment]
Not necessarily bad, can just get hard to read.....

**Comment by grinnellm** [comment]
- [ ] Need to double-check equation subscripts in the Statistical framework (# 1 to 7).
