### ISSUE TITLE
Review subscript order for `x` and `s`

### ISSUE THREAD

**Issue by grinnellm** [grinnellm/SpawnIndex#41]
For equation subscripts,
- `x` is spawn survey type, and
- `s` is spawn number.

Right now the order is `xs` as in `t_{xs}` for transect in spawn survey type `x` and spawn number `s`.
Not sure if this is correct, or if it should be `t_{sx}`.

**Comment by grinnellm** [comment]
Also need to double-check equation subscripts in the Statistical framework (# 1 to 7).
Done.

**Comment by grinnellm** [comment]
In addition, maybe these subscripts should be at the same level, like `{ry}` is now. So, for example, understory spawn index (Eq 32) would change from
`B_{s_{nry}}'`
to
`B_{{sx}_{nry}}'`
(or whatever order I decide for `s` and `x`). Then the total spawn index (Eq 33) would change from
`\sum_{x=1}^X B_{x_{snry}}'`
to
`\sum_{x=1}^X B_{sx_{nry}}'`,
which would align with Figure 3 (except the order is `xs`).

**Comment by grinnellm** [comment]
I think it's correct as is: transect `t` within type `x` within spawn `s`.
But need to sort out subscripts in the spawn level observations/calculations (sections 5.2, 6.3, and 7.3). They jump from sample (5.2) and transect (6.3 and 7.3) level observations/calculations to spawn level, but skip the type `x`. The `x` subscript shows up again in total spawn calculations (section 8).

**Comment by Sages11** [comment]
Does each spawn (s) event only has 1 type (x) survey? 
How are locations (n), regions (r), and years (y) combined?

**Comment by grinnellm** [comment]
A spawn (s) can have 1, 2, or 3 types (x), but usually just 1 or 2 (either surface, or dive (understory and/or Macrocystis)).
